### ISSUE TITLE
Short improvement to "first project"

### ISSUE THREAD

**Issue by ferrandusqui31** [AkshayMokalwar/AkshayMokalwar.github.io#2]
1. On the navigation bar I augmented a bit the padding to make it bigger. I think that (for me) it's visually better.
2. On the sections with class "info" I aligned the text to the left with a margin of 15%.
3. On the contact section, on the boxes I aligned the text vertically and horizontally to the center.

Here are my modifications only to html and css of the folder "first project".
[Modification.zip](https://github.com/AkshayMokalwar/AkshayMokalwar.github.io/files/5288931/Modification.zip)

**Comment by ferrandusqui31** [comment]
You can do the same in second project

**Comment by AkshayMokalwar** [comment]
Thanks you ☺️ buddy  for your suggestions .
I will definitely work on that 👍🏼
